services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # Use this for development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Binds the local frontend directory into the container (incl. hot reload)
      - /app/node_modules # Makes sure the local node_modules don't override the ones in the container
      - /app/.nuxt # Makes sure the local .nuxt directory doesn't override the one in the container
    command: npm run dev # Runs Nuxt in dev mode
