services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NUXT_PUBLIC_BASE_URL: ${NUXT_PUBLIC_BASE_URL}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kanboard:
    image: kanboard/kanboard:latest
    container_name: kanboard
    restart: unless-stopped
    ports:
      - "127.0.0.1:8085:80"
    volumes:
      - ./kanboard/data:/var/www/app/data
      - ./kanboard/plugins:/var/www/app/plugins
      - ./kanboard/adaptive-favicon.svg:/var/www/app/assets/img/adaptive-favicon.svg
    environment:
      - PLUGIN_INSTALLER=false
      - APPLICATION_URL=https://projects.kmapper.ch
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
